coresight: removed unused variable
Remove the unused lock:
error: unused variable 'remote_etm_lock' [-Werror,-Wunused-variable].

Change-Id: Ib5b43a0c095e2245889bd5b7f2ae3d367ef1cb06
Signed-off-by: Kassey Li <quic_yingangl@quicinc.com>