Revert "of/unittest: Disable new dtc node_name_vs_property_name and interrupt_map warnings"
This reverts commit 77f7b266404be778a26fc53704b5ff2b7a477424 as it
breaks the build on clang-based systems with the errors:
	FATAL ERROR: Unrecognized check name "interrupt_map"
	FATAL ERROR: Unrecognized check name "node_name_vs_property_name"

Cc: Rob Herring <robh@kernel.org>
Fixes: 77f7b266404b ("of/unittest: Disable new dtc node_name_vs_property_name and interrupt_map warnings")
Signed-off-by: Greg Kroah-Hartman <gregkh@google.com>
Change-Id: Ia90d9a1d73604f7f1cace2397fc97e3e35ce5b1c