Revert "ANDROID: android: Create debug_symbols driver"
This reverts commit d95d945b79b9e3af7f01ca892497823d406f3580.

Reason for revert: breaks when enabled via config

when building the target `//common-modules/virtual-device:virtual_device_arm_dist`

```
In file included from common/drivers/android/android_debug_symbols.c:12:
common/arch/arm/include/asm/stacktrace.h:41:21: error: call to undeclared function 'in_entry_text'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                frame->ex_frame = in_entry_text(frame->pc);
                                  ^
In file included from common/drivers/android/android_debug_symbols.c:13:
common/arch/arm/include/asm/sections.h:14:20: error: static declaration of 'in_entry_text' follows non-static declaration
static inline bool in_entry_text(unsigned long addr)
                   ^
common/arch/arm/include/asm/stacktrace.h:41:21: note: previous implicit declaration is here
                frame->ex_frame = in_entry_text(frame->pc);
                                  ^
```

Change-Id: Id31003d4c9c60758f6038a63d40ffd7f8044cc9f
Signed-off-by: Matthias Maennich <maennich@google.com>