sched/walt: remove unused cluster_lock
compile error:

__main__/msm-kernel/kernel/sched/walt/walt.c:63:21: error: unused
variable 'cluster_lock' [-Werror,-Wunused-variable]
static DEFINE_MUTEX(cluster_lock).

Change-Id: I50f2118bf209933c25c30ef8fd2cb363ad6e4931
Signed-off-by: Kassey Li <quic_yingangl@quicinc.com>