ANDROID: Fix wrong pr_err type specifier in remove_memory_subsection
Wrong pr_err type specifier causes the following warning:
error: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘u64’ {aka ‘long long unsigned int’} [-Werror=format=]
Fix it by changing to the correct type specifyer for u64.

Fixes: 42db6c2e985b ("ANDROID: mm/memory_hotplug: implement {add/remove}_memory_subsection")
Bug: 170460867
Signed-off-by: Suren Baghdasaryan <surenb@google.com>
Change-Id: Ie00738c159436ecec78cba3818cb3542987186ca
Git-commit: f36d7e344195c0149f7d5e446cabbad7b9a1bb9d
Git-repo: https://android.googlesource.com/kernel/common
Signed-off-by: Chris Goldsworthy <quic_cgoldswo@quicinc.com>