FROMLIST: scripts/sorttable: riscv: fix undelcred identifier 'EM_RISCV' error
Fix the following build break by adding a conditional definition
of EM_RISCV in order to allow cross-compilation on machines
which do not have EM_RISCV definition in their host.

build break log from [1]:
scripts/sorttable.c:352:7: error: use of undeclared identifier 'EM_RISCV'

[1] https://lore.kernel.org/lkml/e8965b25-f15b-c7b4-748c-d207dda9c8e8@i2se.com/

Fixes: 54fed35fd393 ("riscv: Enable BUILDTIME_TABLE_SORT")
Cc: Jisheng Zhang <jszhang@kernel.org>
Reported-by: Stefan Wahren <stefan.wahren@i2se.com>
Tested-by: Stefan Wahren <stefan.wahren@i2se.com>
Reviewed-by: Jisheng Zhang <jszhang@kernel.org>
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Link: https://lore.kernel.org/r/20210913030625.4525-1-miles.chen@mediatek.com
Signed-off-by: Greg Kroah-Hartman <gregkh@google.com>
Change-Id: I597d91c741bfcc0e879908e4e0c8aa114b9ccda4