staging: comedi: Kconfig: Fix COMEDI_TESTS_NI_ROUTES selections
The COMEDI_TESTS_NI_ROUTES option currently selects NI_ROUTING, which
doesn't exist.  It should be selecting COMEDI_NI_ROUTING.  Fix it.

Selecting COMEDI_TESTS_NI_ROUTES without COMEDI_NI_ROUTING resulted in
the following build errors:

ERROR: modpost: "ni_lookup_route_register"
[drivers/staging/comedi/drivers/tests/ni_routes_test.ko] undefined!
ERROR: modpost: "ni_is_cmd_dest"
[drivers/staging/comedi/drivers/tests/ni_routes_test.ko] undefined!
ERROR: modpost: "ni_find_route_source"
[drivers/staging/comedi/drivers/tests/ni_routes_test.ko] undefined!
ERROR: modpost: "ni_get_valid_routes"
[drivers/staging/comedi/drivers/tests/ni_routes_test.ko] undefined!
ERROR: modpost: "ni_count_valid_routes"
[drivers/staging/comedi/drivers/tests/ni_routes_test.ko] undefined!
ERROR: modpost: "ni_sort_device_routes"
[drivers/staging/comedi/drivers/tests/ni_routes_test.ko] undefined!
ERROR: modpost: "ni_assign_device_routes"
[drivers/staging/comedi/drivers/tests/ni_routes_test.ko] undefined!
ERROR: modpost: "ni_find_route_set"
[drivers/staging/comedi/drivers/tests/ni_routes_test.ko] undefined!
ERROR: modpost: "ni_route_set_has_source"
[drivers/staging/comedi/drivers/tests/ni_routes_test.ko] undefined!
ERROR: modpost: "ni_route_to_register"
[drivers/staging/comedi/drivers/tests/ni_routes_test.ko] undefined!

Reported-by: kernel test robot <lkp@intel.com>
Fixes: c82b130616e3 ("staging: comedi: Add Kconfig options to build unit test modules")
Signed-off-by: Ian Abbott <abbotti@mev.co.uk>
Link: https://lore.kernel.org/r/20210409110844.148378-1-abbotti@mev.co.uk
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>