virt: gunyah: remove unused lock
drivers/virt/gunyah/gh_rm_core.c:89:21: error: unused variable 'gh_rm_call_idr_lock' [-Werror,-Wunused-variable]
static DEFINE_MUTEX(gh_rm_call_idr_lock);
                    ^
drivers/virt/gunyah/gh_rm_core.c:92:21: error: unused variable 'gh_rm_send_lock' [-Werror,-Wunused-variable]
static DEFINE_MUTEX(gh_rm_send_lock);
		    ^

Change-Id: Ic8d5b62a5e0185330231ce0fb6964ee3423eef53
Signed-off-by: Kassey Li <quic_yingangl@quicinc.com>